# Generated by Django 2.1.1 on 2018-09-19 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20180919_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecommentvotes',
            name='comment',
            field=models.ForeignKey(default=None, on_delete='CASCADE', to='articles.ArticleComments'),
        ),
    ]
