# Generated by Django 2.1.1 on 2018-09-19 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20180919_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlecommentvotes',
            name='article',
        ),
    ]
