# Generated by Django 2.1.1 on 2018-09-19 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_remove_articlecommentvotes_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecommentvotes',
            name='comment',
            field=models.ForeignKey(on_delete='CASCADE', to='articles.ArticleComments'),
        ),
    ]
