# Generated by Django 2.1.1 on 2018-09-29 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_auto_20180929_0928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='categorie_id',
        ),
        migrations.DeleteModel(
            name='Categorie',
        ),
    ]
