# Generated by Django 2.1.1 on 2018-09-18 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='answervotes',
            table='answer_votes',
        ),
    ]
