# Generated by Django 2.1.1 on 2018-09-29 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
        ('topics', '0002_auto_20180920_1211'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed.CategoriesMaster')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topics.Topics')),
            ],
            options={
                'verbose_name_plural': 'Topic Categories',
                'db_table': 'topic_categories',
            },
        ),
    ]
